In [57]:
import numpy as np 
import pandas as pd

import seaborn as sns 
import matplotlib.pyplot as plt


import warnings
warnings.filterwarnings("ignore")

In [58]:
df=pd.read_csv('CO2 Emissions_Canada.csv')

In [59]:
df.head()

Make       Model Vehicle Class  Engine Size(L)  Cylinders Transmission  \
0  ACURA         ILX       COMPACT             2.0          4          AS5   
1  ACURA         ILX       COMPACT             2.4          4           M6   
2  ACURA  ILX HYBRID       COMPACT             1.5          4          AV7   
3  ACURA     MDX 4WD   SUV - SMALL             3.5          6          AS6   
4  ACURA     RDX AWD   SUV - SMALL             3.5          6          AS6   

  Fuel Type  Fuel Consumption City (L/100 km)  \
0         Z                               9.9   
1         Z                              11.2   
2         Z                               6.0   
3         Z                              12.7   
4         Z                              12.1   

   Fuel Consumption Hwy (L/100 km)  Fuel Consumption Comb (L/100 km)  \
0                              6.7                               8.5   
1                              7.7                               9.6   
2                              5.8                               5.9   
3                              9.1                              11.1   
4                              8.7                              10.6   

   Fuel Consumption Comb (mpg)  CO2 Emissions(g/km)  
0                           33                  196  
1                           29                  221  
2                           48                  136  
3                           25                  255  
4                           27                  244

In [60]:
df.shape

(7385, 12)

In [61]:
df.isnull().sum()

Make                                0
Model                               0
Vehicle Class                       0
Engine Size(L)                      0
Cylinders                           0
Transmission                        0
Fuel Type                           0
Fuel Consumption City (L/100 km)    0
Fuel Consumption Hwy (L/100 km)     0
Fuel Consumption Comb (L/100 km)    0
Fuel Consumption Comb (mpg)         0
CO2 Emissions(g/km)                 0
dtype: int64

In [62]:
df.duplicated().sum()

1103

In [63]:
df= df.drop_duplicates()
df.shape

(6282, 12)

In [64]:
df.duplicated().sum()

0

In [65]:
df.to_csv('co2emissions.csv')

In [9]:
df.corr()

Engine Size(L)  Cylinders  \
Engine Size(L)                          1.000000   0.928843   
Cylinders                               0.928843   1.000000   
Fuel Consumption City (L/100 km)        0.834228   0.801277   
Fuel Consumption Hwy (L/100 km)         0.766817   0.717647   
Fuel Consumption Comb (L/100 km)        0.820146   0.781099   
Fuel Consumption Comb (mpg)            -0.762955  -0.723731   
CO2 Emissions(g/km)                     0.854802   0.834687   

                                  Fuel Consumption City (L/100 km)  \
Engine Size(L)                                            0.834228   
Cylinders                                                 0.801277   
Fuel Consumption City (L/100 km)                          1.000000   
Fuel Consumption Hwy (L/100 km)                           0.950811   
Fuel Consumption Comb (L/100 km)                          0.994052   
Fuel Consumption Comb (mpg)                              -0.927640   
CO2 Emissions(g/km)                                       0.918756   

                                  Fuel Consumption Hwy (L/100 km)  \
Engine Size(L)                                           0.766817   
Cylinders                                                0.717647   
Fuel Consumption City (L/100 km)                         0.950811   
Fuel Consumption Hwy (L/100 km)                          1.000000   
Fuel Consumption Comb (L/100 km)                         0.978607   
Fuel Consumption Comb (mpg)                             -0.891892   
CO2 Emissions(g/km)                                      0.883424   

                                  Fuel Consumption Comb (L/100 km)  \
Engine Size(L)                                            0.820146   
Cylinders                                                 0.781099   
Fuel Consumption City (L/100 km)                          0.994052   
Fuel Consumption Hwy (L/100 km)                           0.978607   
Fuel Consumption Comb (L/100 km)                          1.000000   
Fuel Consumption Comb (mpg)                              -0.925801   
CO2 Emissions(g/km)                                       0.916840   

                                  Fuel Consumption Comb (mpg)  \
Engine Size(L)                                      -0.762955   
Cylinders                                           -0.723731   
Fuel Consumption City (L/100 km)                    -0.927640   
Fuel Consumption Hwy (L/100 km)                     -0.891892   
Fuel Consumption Comb (L/100 km)                    -0.925801   
Fuel Consumption Comb (mpg)                          1.000000   
CO2 Emissions(g/km)                                 -0.906783   

                                  CO2 Emissions(g/km)  
Engine Size(L)                               0.854802  
Cylinders                                    0.834687  
Fuel Consumption City (L/100 km)             0.918756  
Fuel Consumption Hwy (L/100 km)              0.883424  
Fuel Consumption Comb (L/100 km)             0.916840  
Fuel Consumption Comb (mpg)                 -0.906783  
CO2 Emissions(g/km)                          1.000000

In [10]:
df2 = df.drop(['Make','Model','Vehicle Class','Fuel Consumption City (L/100 km)', 'Transmission', 'Fuel Type', 'Fuel Consumption Hwy (L/100 km)','Fuel Consumption Comb (mpg)'],axis=1)
df2.head()

Engine Size(L)  Cylinders  Fuel Consumption Comb (L/100 km)  \
0             2.0          4                               8.5   
1             2.4          4                               9.6   
2             1.5          4                               5.9   
3             3.5          6                              11.1   
4             3.5          6                              10.6   

   CO2 Emissions(g/km)  
0                  196  
1                  221  
2                  136  
3                  255  
4                  244

In [44]:
X = df2.drop(['CO2 Emissions(g/km)'], axis= 1)
y = df2["CO2 Emissions(g/km)"]

In [20]:
#X_train=X
#y_train=y

In [45]:
from sklearn.model_selection import train_test_split, cross_val_score, cross_val_predict
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(random_state = 42)
rf.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [24]:
X_train[:1]

Engine Size(L)  Cylinders  Fuel Consumption Comb (L/100 km)
0             2.0          4                               8.5

In [27]:
#3.5	6	11.1	255
x_test=np.array([[3.5,6,11]])

In [46]:
y_prediction=rf.predict(X_test)

In [47]:
y_prediction

array([287.370415  , 246.72101626, 298.78794092, ..., 283.005     ,
       263.81312118, 263.89677778])

In [48]:
from sklearn.metrics import r2_score
forest_score=r2_score(y_test,y_prediction)
print(forest_score)

0.9716591590111995


In [52]:
### Giving Inputs
# 244
x_test=np.array([[3.5,6,11]])

In [53]:
y_prediction=rf.predict(x_test)

In [54]:
y_prediction

array([256.53353077])

In [55]:
#1.5	4	5.9	
#136
x_test=([[1.5,4,5.9]])

In [56]:
y_prediction=rf.predict(x_test)
y_prediction

array([136.6827619])